# Generated by Django 3.2.9 on 2021-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=70)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
