# Generated by Django 3.2.9 on 2021-12-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pdf',
            table='pdf',
        ),
    ]
