# Generated by Django 3.2.9 on 2021-12-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pdf_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=70, verbose_name='search_name')),
                ('file_path', models.CharField(max_length=70, verbose_name='file_path')),
                ('search_query', models.TextField(blank=True, max_length=1000, null=True, verbose_name='search_query')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='content',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='コンテンツ'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file_name',
            field=models.CharField(max_length=70, verbose_name='ファイル名'),
        ),
    ]
